#pragma once



#include "hdefbase.h"



namespace h
{
	DLL_DECL_INTERFACE(h_F3DCamera)
	{
		INTERFACE_DECL_FUNC_T(VOID, multiply)		(CONST FLOAT mMatrix[16])PURE;
		INTERFACE_DECL_FUNC_T(VOID, move_XDir)		(CONST FLOAT value)PURE;
		INTERFACE_DECL_FUNC_T(VOID, move_YDir)		(CONST FLOAT value)PURE;
		INTERFACE_DECL_FUNC_T(VOID, move_ZDir)		(CONST FLOAT value)PURE;
		INTERFACE_DECL_FUNC_T(VOID, rotate_XAxis)	(CONST FLOAT angle)PURE;
		INTERFACE_DECL_FUNC_T(VOID, rotate_YAxis)	(CONST FLOAT angle)PURE;
		INTERFACE_DECL_FUNC_T(VOID, rotate_ZAxis)	(CONST FLOAT angle)PURE;
		INTERFACE_DECL_FUNC_T(VOID, get_XDir)		(FLOAT vXdir[3])CONST PURE;
		INTERFACE_DECL_FUNC_T(VOID, get_YDir)		(FLOAT vYdir[3])CONST PURE;
		INTERFACE_DECL_FUNC_T(VOID, get_ZDir)		(FLOAT vZdir[3])CONST PURE;
		INTERFACE_DECL_FUNC_T(VOID, get_Position)	(FLOAT vPos[3])CONST PURE;
		INTERFACE_DECL_FUNC_T(VOID, set_Position)	(CONST FLOAT vPos[3])PURE;
		INTERFACE_DECL_FUNC_T(VOID, set_Target)		(CONST FLOAT vPos[3])PURE;
		INTERFACE_DECL_FUNC_T(VOID, get_ViewMatrix)	(FLOAT mView[16])CONST PURE;
	} *ptr_F3DCAMERA;
};